import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcryptjs";
import { getMissingRequiredAttributes } from "../src/lib/catalog-attribute-schema";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database for Aqua Still Zlatibor...");

  // 1. Categories
  const categoriesData = [
    { id: "cat-alati", name: "Alati i oprema", slug: "alati", description: "Profesionalni električni, akumulatorski i ručni alati, pribor, merni alati i oprema za radionicu.", itemCount: 0, iconName: "wrench" },
    { id: "cat-vodovod", name: "Vodovod i kanalizacija", slug: "vodovod", description: "Cevi, fiting, ventili, slavine, odvodnja, pumpe, vodomeri i montažni materijal za instalacije vode.", itemCount: 0, iconName: "droplet" },
    { id: "cat-kupatila", name: "Kupatilska oprema i sanitarije", slug: "kupatila", description: "Slavine, tuševi, sanitarije, ugradni sistemi, kupatilski nameštaj, oprema i galanterija.", itemCount: 0, iconName: "bath" },
    { id: "cat-navodnjavanje", name: "Navodnjavanje i bašta", slug: "navodnjavanje", description: "Kap po kap sistemi, prskalice, pumpe, creva, spojnice i automatika za baštu, voćnjak i plastenik.", itemCount: 0, iconName: "sprout" },
    { id: "cat-grejanje", name: "Grejanje", slug: "grejanje", description: "Radijatori, ventili, termostatska regulacija, cevi i pribor za sisteme grejanja.", itemCount: 0, iconName: "flame" },
    { id: "cat-boje-hemija", name: "Boje, lakovi, lepkovi i hemija", slug: "boje-lakovi-hemija", description: "Boje, lakovi, impregnacije, silikoni, pur-pene, lepkovi, trake i hidroizolacioni materijali.", itemCount: 0, iconName: "paintbrush" },
    { id: "cat-rasveta-elektro", name: "Elektro-oprema i rasveta", slug: "rasveta-elektro-oprema", description: "LED rasveta, kablovi, produžni kablovi, sklopke, utičnice i elektro pribor.", itemCount: 0, iconName: "lightbulb" },
    { id: "cat-vijcana-roba", name: "Vijčana roba i pričvrsni materijal", slug: "vijcana-roba", description: "Šrafovi, tiplovi, ekseri, matice, podloške i elementi za pričvršćivanje i montažu.", itemCount: 0, iconName: "nut" },
    { id: "cat-gradjevinska-oprema", name: "Građevinska i zaštitna oprema", slug: "gradjevinska-zastitna-oprema", description: "Merdevine, građevinska kolica, mešalice, ručni građevinski alat i lična zaštitna oprema.", itemCount: 0, iconName: "hard-hat" },
    { id: "cat-kuca-dvoriste", name: "Kuća, dvorište i čišćenje", slug: "kuca-dvoriste-ciscenje", description: "Oprema za domaćinstvo, dvorište, čišćenje, skladištenje i baštenske potrebe.", itemCount: 0, iconName: "house" },
  ];

  for (const cat of categoriesData) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: { name: cat.name, description: cat.description },
      create: cat,
    });
  }

  // 2. Subcategories
  const subcategoriesData = [
    { id: "sub-aku-busilice", categoryId: "cat-alati", name: "Aku bušilice i odvijači", slug: "aku-busilice", itemCount: 0 },
    { id: "sub-brusilice", categoryId: "cat-alati", name: "Ugaone brusilice", slug: "brusilice", itemCount: 0 },
    { id: "sub-testere", categoryId: "cat-alati", name: "Testere i cirkulari", slug: "testere", itemCount: 0 },
    { id: "sub-rucni-alat", categoryId: "cat-alati", name: "Ručni alati i ključevi", slug: "rucni-alat", itemCount: 0 },
    { id: "sub-odvijaci", categoryId: "cat-alati", name: "Odvijači i bitovi", slug: "odvijaci-bitovi", itemCount: 0 },
    { id: "sub-klesta", categoryId: "cat-alati", name: "Klešta i sečice", slug: "klesta-secice", itemCount: 0 },
    { id: "sub-sekire-cekici", categoryId: "cat-alati", name: "Sekire i čekići", slug: "sekire-cekici", itemCount: 0 },
    { id: "sub-garniture-rucnog-alata", categoryId: "cat-alati", name: "Garniture ručnog alata", slug: "garniture-rucnog-alata", itemCount: 0 },
    { id: "sub-pribor-alati", categoryId: "cat-alati", name: "Pribor za električne alate", slug: "pribor-za-alate", itemCount: 0 },
    { id: "sub-merni-alat", categoryId: "cat-alati", name: "Merni i obeležavajući alat", slug: "merni-alat", itemCount: 0 },
    { id: "sub-tolsen-rucni", categoryId: "cat-alati", name: "Tolsen i ostali ručni alati", slug: "tolsen-rucni-alati", itemCount: 0 },
    { id: "sub-cevi", categoryId: "cat-vodovod", name: "Cevi", slug: "cevi", itemCount: 0 },
    { id: "sub-fiting", categoryId: "cat-vodovod", name: "Fiting i spojnice", slug: "fiting", itemCount: 0 },
    { id: "sub-ventili", categoryId: "cat-vodovod", name: "Ventili, zasuni i slavine", slug: "ventili", itemCount: 0 },
    { id: "sub-odvodnja", categoryId: "cat-vodovod", name: "Odvodnja, sifoni i slivnici", slug: "odvodnja-sifoni", itemCount: 0 },
    { id: "sub-pumpe-voda", categoryId: "cat-vodovod", name: "Pumpe za vodu i hidrofori", slug: "pumpe-za-vodu", itemCount: 0 },
    { id: "sub-zaptivni-materijal", categoryId: "cat-vodovod", name: "Zaptivni i montažni materijal", slug: "zaptivni-montazni-materijal", itemCount: 0 },
    { id: "sub-vodomeri", categoryId: "cat-vodovod", name: "Vodomer i regulacija", slug: "vodomeri-regulacija", itemCount: 0 },
    { id: "sub-vodovodni-alat", categoryId: "cat-vodovod", name: "Vodovodni alat", slug: "vodovodni-alat", itemCount: 0 },
    { id: "sub-cevna-izolacija", categoryId: "cat-vodovod", name: "Izolacija i nosači cevi", slug: "izolacija-nosaci-cevi", itemCount: 0 },
    { id: "sub-baterije", categoryId: "cat-kupatila", name: "Slavine i baterije", slug: "slavine-i-baterije", itemCount: 0 },
    { id: "sub-sanitarije", categoryId: "cat-kupatila", name: "WC šolje i sanitarije", slug: "sanitarije", itemCount: 0 },
    { id: "sub-ugradni-sistemi", categoryId: "cat-kupatila", name: "Ugradni sistemi i vodokotlići", slug: "ugradni-sistemi", itemCount: 0 },
    { id: "sub-tus-program", categoryId: "cat-kupatila", name: "Tuševi i tuš program", slug: "tus-program", itemCount: 0 },
    { id: "sub-tus-kabine", categoryId: "cat-kupatila", name: "Tuš kabine i paravani", slug: "tus-kabine", itemCount: 0 },
    { id: "sub-lavaboi", categoryId: "cat-kupatila", name: "Lavaboi", slug: "lavaboi", itemCount: 0 },
    { id: "sub-kade", categoryId: "cat-kupatila", name: "Kade i oprema za kade", slug: "kade", itemCount: 0 },
    { id: "sub-namestaj", categoryId: "cat-kupatila", name: "Kupatilski nameštaj", slug: "kupatilski-namestaj", itemCount: 0 },
    { id: "sub-kupatilski-pribor", categoryId: "cat-kupatila", name: "Kupatilski pribor i galanterija", slug: "kupatilski-pribor", itemCount: 0 },
    { id: "sub-ogledala", categoryId: "cat-kupatila", name: "Ogledala i ogledalni ormarići", slug: "ogledala", itemCount: 0 },
    { id: "sub-odvodi", categoryId: "cat-kupatila", name: "Kanalice, slivnici i odvodi", slug: "kupatilski-odvodi", itemCount: 0 },
    { id: "sub-kap-po-kap", categoryId: "cat-navodnjavanje", name: "Kap po kap sistemi", slug: "kap-po-kap", itemCount: 0 },
    { id: "sub-prskalice", categoryId: "cat-navodnjavanje", name: "Rasprskivači i rotori", slug: "prskalice", itemCount: 0 },
    { id: "sub-creva", categoryId: "cat-navodnjavanje", name: "Baštenska i tehnička creva", slug: "creva", itemCount: 0 },
    { id: "sub-automatika", categoryId: "cat-navodnjavanje", name: "Elektroventili i tajmeri", slug: "automatika", itemCount: 0 },
    { id: "sub-navodnjavanje-fiting", categoryId: "cat-navodnjavanje", name: "Spojnice i fiting za navodnjavanje", slug: "navodnjavanje-fiting", itemCount: 0 },
    { id: "sub-pumpe-navodnjavanje", categoryId: "cat-navodnjavanje", name: "Pumpe za navodnjavanje", slug: "pumpe-navodnjavanje", itemCount: 0 },
    { id: "sub-filteri-navodnjavanje", categoryId: "cat-navodnjavanje", name: "Filteri i regulacija pritiska", slug: "filteri-regulacija", itemCount: 0 },
    { id: "sub-basta-oprema", categoryId: "cat-navodnjavanje", name: "Baštenska oprema i pribor", slug: "basta-oprema", itemCount: 0 },
    { id: "sub-grejna-tela", categoryId: "cat-grejanje", name: "Radijatori i grejna tela", slug: "radijatori-grejna-tela", itemCount: 0 },
    { id: "sub-ventili-grejanje", categoryId: "cat-grejanje", name: "Ventili i termostatska regulacija", slug: "ventili-termostatska-regulacija", itemCount: 0 },
    { id: "sub-pribor-grejanje", categoryId: "cat-grejanje", name: "Pribor za grejanje", slug: "pribor-za-grejanje", itemCount: 0 },
    { id: "sub-cevi-grejanje", categoryId: "cat-grejanje", name: "Cevi i fiting za grejanje", slug: "cevi-fiting-grejanje", itemCount: 0 },
    { id: "sub-pumpe-grejanje", categoryId: "cat-grejanje", name: "Cirkulacione pumpe", slug: "cirkulacione-pumpe", itemCount: 0 },
    { id: "sub-elektricne-busilice", categoryId: "cat-alati", name: "Električne bušilice i odvijači", slug: "elektricne-busilice-odvijaci", itemCount: 0 },
    { id: "sub-elektricne-brusilice", categoryId: "cat-alati", name: "Električne brusilice", slug: "elektricne-brusilice", itemCount: 0 },
    { id: "sub-burgije", categoryId: "cat-alati", name: "Burgije i pribor za bušenje", slug: "burgije-pribor-busenje", itemCount: 0 },
    { id: "sub-brusne-ploce", categoryId: "cat-alati", name: "Brusne i rezne ploče", slug: "brusne-rezne-ploce", itemCount: 0 },
    { id: "sub-mesalice", categoryId: "cat-gradjevinska-oprema", name: "Mešalice za boju i malter", slug: "mesalice-boju-malter", itemCount: 0 },
    { id: "sub-elektro-pumpe", categoryId: "cat-alati", name: "Električne pumpe i ventilatori", slug: "elektricne-pumpe-ventilatori", itemCount: 0 },
    { id: "sub-boje-zidne", categoryId: "cat-boje-hemija", name: "Boje za zidove", slug: "boje-za-zidove", itemCount: 0 },
    { id: "sub-lakovi-impregnacije", categoryId: "cat-boje-hemija", name: "Lakovi i impregnacije", slug: "lakovi-impregnacije", itemCount: 0 },
    { id: "sub-silikoni-pur-pene", categoryId: "cat-boje-hemija", name: "Silikoni i pur-pene", slug: "silikoni-pur-pene", itemCount: 0 },
    { id: "sub-lepkovi-trake", categoryId: "cat-boje-hemija", name: "Lepkovi i trake", slug: "lepkovi-krep-trake", itemCount: 0 },
    { id: "sub-hidroizolacija", categoryId: "cat-boje-hemija", name: "Hidroizolacioni materijali", slug: "hidroizolacija", itemCount: 0 },
    { id: "sub-zaptivne-mase", categoryId: "cat-boje-hemija", name: "Zaptivne mase i kitovi", slug: "zaptivne-mase", itemCount: 0 },
    { id: "sub-led-rasveta", categoryId: "cat-rasveta-elektro", name: "LED rasveta", slug: "led-rasveta", itemCount: 0 },
    { id: "sub-kablovi", categoryId: "cat-rasveta-elektro", name: "Kablovi i produžni kablovi", slug: "kablovi-produzni", itemCount: 0 },
    { id: "sub-sklopke", categoryId: "cat-rasveta-elektro", name: "Sklopke, utičnice i elektro-pribor", slug: "sklopke-elektro-pribor", itemCount: 0 },
    { id: "sub-baterije-elektro", categoryId: "cat-rasveta-elektro", name: "Baterije i akumulatori", slug: "elektro-baterije", itemCount: 0 },
    { id: "sub-merenje-elektro", categoryId: "cat-rasveta-elektro", name: "Merni i ispitni uređaji", slug: "merni-ispitni-uredjaji", itemCount: 0 },
    { id: "sub-srafovi-tiplovi", categoryId: "cat-vijcana-roba", name: "Šrafovi i tiplovi", slug: "srafovi-tiplovi", itemCount: 0 },
    { id: "sub-ekseri", categoryId: "cat-vijcana-roba", name: "Ekseri", slug: "ekseri", itemCount: 0 },
    { id: "sub-matice-podloske", categoryId: "cat-vijcana-roba", name: "Matice i podloške", slug: "matice-podloske", itemCount: 0 },
    { id: "sub-metalni-elementi", categoryId: "cat-vijcana-roba", name: "Metalni elementi za pričvršćivanje", slug: "metalni-elementi-pricvrscivanje", itemCount: 0 },
    { id: "sub-ankeri", categoryId: "cat-vijcana-roba", name: "Ankeri i specijalno pričvršćivanje", slug: "ankeri-specijalno-pricvrscivanje", itemCount: 0 },
    { id: "sub-merdevine", categoryId: "cat-gradjevinska-oprema", name: "Merdevine i platforme", slug: "merdevine", itemCount: 0 },
    { id: "sub-kolica", categoryId: "cat-gradjevinska-oprema", name: "Građevinska kolica", slug: "gradjevinska-kolica", itemCount: 0 },
    { id: "sub-mesalice-beton", categoryId: "cat-gradjevinska-oprema", name: "Mešalice za beton", slug: "mesalice-za-beton", itemCount: 0 },
    { id: "sub-zastitna-oprema", categoryId: "cat-gradjevinska-oprema", name: "Radne rukavice i zaštitna oprema", slug: "radne-rukavice-zastitna-oprema", itemCount: 0 },
    { id: "sub-gradjevinski-alat", categoryId: "cat-gradjevinska-oprema", name: "Građevinski i zidarski alat", slug: "gradjevinski-alat", itemCount: 0 },
    { id: "sub-ciscenje", categoryId: "cat-kuca-dvoriste", name: "Četke i oprema za čišćenje", slug: "cetke-oprema-ciscenje", itemCount: 0 },
    { id: "sub-kante-kanisteri", categoryId: "cat-kuca-dvoriste", name: "Kante i kanisteri", slug: "kante-kanisteri", itemCount: 0 },
    { id: "sub-uzad-kace-burad", categoryId: "cat-kuca-dvoriste", name: "Užad, kace i burad", slug: "uzad-kace-burad", itemCount: 0 },
    { id: "sub-dvoriste", categoryId: "cat-kuca-dvoriste", name: "Oprema za dvorište", slug: "oprema-za-dvoriste", itemCount: 0 },
    { id: "sub-skladistenje", categoryId: "cat-kuca-dvoriste", name: "Kutije, posude i skladištenje", slug: "skladistenje", itemCount: 0 },
  ];

  for (const sub of subcategoriesData) {
    await prisma.subcategory.upsert({
      where: { id: sub.id },
      update: { name: sub.name },
      create: sub,
    });
  }

  // 3. Brands
  const brandsData = [
    { id: "brand-makita", name: "Makita", slug: "makita" },
    { id: "brand-bosch", name: "Bosch", slug: "bosch" },
    { id: "brand-dewalt", name: "DeWalt", slug: "dewalt" },
    { id: "brand-unior", name: "Unior", slug: "unior" },
    { id: "brand-pestan", name: "Peštan", slug: "pestan" },
    { id: "brand-valvex", name: "Valvex", slug: "valvex" },
    { id: "brand-pedrollo", name: "Pedrollo", slug: "pedrollo" },
    { id: "brand-grohe", name: "Grohe", slug: "grohe" },
    { id: "brand-hansgrohe", name: "Hansgrohe", slug: "hansgrohe" },
    { id: "brand-geberit", name: "Geberit", slug: "geberit" },
    { id: "brand-rain-bird", name: "Rain Bird", slug: "rain-bird" },
    { id: "brand-gardena", name: "Gardena", slug: "gardena" },
    { id: "brand-hunter", name: "Hunter", slug: "hunter" },
    { id: "brand-tolsen", name: "Tolsen", slug: "tolsen" },
  ];

  for (const brand of brandsData) {
    await prisma.brand.upsert({
      where: { id: brand.id },
      update: { name: brand.name },
      create: brand,
    });
  }

  // 4. Products
  const productsData = [
    {
      id: "prod-1",
      sku: "MAK-DHP485Z",
      barcode: "0088381866385",
      name: "Makita DHP485Z Aku udarna bušilica-odvijač 18V (bez baterije i punjača)",
      slug: "makita-dhp485z-aku-udarna-busilica-18v",
      brand: "Makita",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "aku-busilice",
      subcategoryName: "Aku bušilice i odvijači",
      price: 13990,
      salePrice: 11990,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 18,
      wmsLocation: "A-03-02-04",
      shortDescription: "Snažna udarna bušilica sa motorom bez četkica (Brushless), 50 Nm obrtnog momenta.",
      description: "Makita DHP485Z je kompaktna i izuzetno izdržljiva akumulatorska udarna bušilica. Opremljena je motorom bez četkica koji omogućava veću autonomiju rada i duži vek trajanja. Poseduje metalnu brzosteznu glavu 13mm i dvobrzinski prenosnik.",
      images: ["/placeholder-tool.svg"],
      attributes: { napon: "18V", motor: "Brushless (bez četkica)", prihvat: "13 mm", obrtni_moment: "50 Nm", broj_obrtaja: "0-500 / 0-1.900 min-1" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-2",
      sku: "BOS-GSB18V50",
      barcode: "3165140982900",
      name: "Bosch Professional GSB 18V-50 Akumulatorska udarna bušilica",
      slug: "bosch-professional-gsb-18v-50-aku-busilica",
      brand: "Bosch",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "aku-busilice",
      subcategoryName: "Aku bušilice i odvijači",
      price: 17490,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 12,
      wmsLocation: "A-03-02-05",
      shortDescription: "Robustan motor bez četkica za teške poslove bušenja u zidu, drvetu i metalu.",
      description: "Inteligentni Brushless motor direktno komunicira sa elektronikom alata za optimalan rad i zaštitu od preopterećenja. Metalni futer 13 mm pruža maksimalan prenos snage.",
      images: ["/placeholder-tool.svg"],
      attributes: { napon: "18V", motor: "Brushless (bez četkica)", prihvat: "13 mm", obrtni_moment: "50 Nm" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-3",
      sku: "DEW-DWE4206",
      barcode: "5035048538203",
      name: "DeWalt DWE4206 Ugaona električna brusilica 115mm 1010W",
      slug: "dewalt-dwe4206-ugaona-brusilica-115mm-1010w",
      brand: "DeWalt",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "brusilice",
      subcategoryName: "Ugaone brusilice",
      price: 10490,
      salePrice: 9190,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 24,
      wmsLocation: "A-01-04-02",
      shortDescription: "Kompaktna ugaona brusilica visoke efikasnosti sa No-Volt Release zaštitom.",
      description: "Sistem za izbacivanje prašine uklanja većinu čestica iz vazduha koji prolazi kroz motor, sprečavajući oštećenja i habanje. Meki start smanjuje trzaj pri pokretanju.",
      images: ["/placeholder-tool.svg"],
      attributes: { snaga: "850W - 1200W", napon: "230V", prihvat: "M14" },
      isFeatured: false,
      isPromo: true,
    },
    {
      id: "prod-4",
      sku: "UNI-1201CB",
      barcode: "3838909120150",
      name: "Unior Garnitura viljuškasto-okastih ključeva u kartonu 6-22mm (17 kom)",
      slug: "unior-garnitura-viljuskasto-okastih-kljuceva-6-22mm",
      brand: "Unior",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "rucni-alat",
      subcategoryName: "Ručni alati i ključevi",
      price: 15890,
      salePrice: null,
      vatRate: 0.20,
      unit: "pak",
      inStock: true,
      stockQuantity: 9,
      wmsLocation: "A-02-01-08",
      shortDescription: "Hrom-vanadijumski kovani ključevi krunisani po DIN 3113 standardu.",
      description: "Unior profesionalni ključevi izradjeni od vrhunskog hrom-vanadijum čelika, kovani i u celosti ojačani. Dugovečan i pouzdan radionički komplet.",
      images: ["/placeholder-tool.svg"],
      attributes: { materijal: "Hrom-vanadijum", broj_delova: "17 komada (6-22 mm)" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-5",
      sku: "PES-3SK110-1000",
      barcode: "8605012304912",
      name: "Peštan 3P Niskošumna kanalizaciona cev fi 110 x 1000 mm",
      slug: "pestan-3p-niskosumna-kanalizaciona-cev-110-1000",
      brand: "Peštan",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "cevi",
      subcategoryName: "Cevi",
      price: 940,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 140,
      wmsLocation: "B-01-01-01",
      shortDescription: "Troslojna bešumna cev za unutrašnju kanalizaciju sa integrisanom zaptivkom.",
      description: "Peštan 3P cevi izrađene su od mineralno ojačanog polipropilena. Pružaju znatno smanjenje buke protoka otpadnih voda i visoku otpornost na hemikalije i toplotu.",
      images: ["/placeholder-pipe.svg"],
      attributes: { precnik: "fi 110", materijal: "PP mineralno ojačan", duzina: "1000 mm" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-6",
      sku: "PES-PPR25-PN20",
      barcode: "8605012308821",
      name: "Peštan PP-R Cev za toplu i hladnu vodu fi 25 mm PN20 (4m)",
      slug: "pestan-ppr-cev-fi-25mm-pn20-4m",
      brand: "Peštan",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "cevi",
      subcategoryName: "Cevi",
      price: 490,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 220,
      wmsLocation: "B-01-02-03",
      shortDescription: "Polipropilenska cev za vodovodne instalacije, pritisak PN20.",
      description: "Ekološki materijal otporan na kamenac i koroziju. Koristi se za instalaciju pijaće tople i hladne vode u stambenim i industrijskim objektima.",
      images: ["/placeholder-pipe.svg"],
      attributes: { precnik: "fi 25", materijal: "PP-R", pritisak: "PN 20" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-7",
      sku: "VAL-KV12-LEP",
      barcode: "5901234567891",
      name: "Valvex Kugla ventil sa leptir ručkom 1/2\" PN30 Ž-Ž",
      slug: "valvex-kugla-ventil-leptir-rucka-1-2-pn30",
      brand: "Valvex",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "ventili",
      subcategoryName: "Ventili, zasuni i slavine",
      price: 680,
      salePrice: 590,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 85,
      wmsLocation: "B-03-01-14",
      shortDescription: "Mesingani kuglasti ventil sa punim protokom i crvenom leptir ručkom.",
      description: "Visokokvalitetni ventil za vodu i grejanje, testiran na radni pritisak do 30 bara. Telo od kovanog niklovanog mesinga.",
      images: ["/placeholder-valve.svg"],
      attributes: { precnik: "1/2\"", materijal: "Mesing", pritisak: "PN 30" },
      isFeatured: false,
      isPromo: true,
    },
    {
      id: "prod-8",
      sku: "PED-TOP2",
      barcode: "8056789012345",
      name: "Pedrollo TOP 2 Potapajuća drenažna pumpa za čistu vodu",
      slug: "pedrollo-top-2-potapajuca-pumpa",
      brand: "Pedrollo",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "pumpe-voda",
      subcategoryName: "Pumpe za vodu i hidrofori",
      price: 18990,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 7,
      wmsLocation: "B-04-03-01",
      shortDescription: "Italijanska potapajuća pumpa kapaciteta do 220 l/min (13.2 m³/h).",
      description: "Pedrollo TOP 2 je pogodna za drenažu bistre vode bez abrazivnih čestica. Odlična za pražnjenje poplavljenih podruma, rezervoara i bazena.",
      images: ["/placeholder-pump.svg"],
      attributes: { snaga: "370W", protok: "2000+ l/h", materijal: "Tehopolimer / Inox" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-9",
      sku: "GRO-32815000",
      barcode: "4005176883204",
      name: "Grohe BauLoop Jednoručna stojeća slavina za lavabo",
      slug: "grohe-bauloop-jednorucna-slavina-za-lavabo",
      brand: "Grohe",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "baterije",
      subcategoryName: "Slavine i baterije",
      price: 7990,
      salePrice: 6690,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 32,
      wmsLocation: "C-01-02-03",
      shortDescription: "Elegantna baterija sa Grohe Long-Life hromiranom obradom i EcoJoy perlatorom.",
      description: "Grohe BauLoop kombinuje moderan minimalistički dizajn sa vrhunskom tehnologijom. Opremljena je keramičkim mešačem 28 mm i perlatorom koji štedi do 50% vode.",
      images: ["/placeholder-faucet.svg"],
      attributes: { zavrsna_obrada: "Hrom sjaj", montaza: "Stojeća (na lavabo)", kartusa: "Keramički 28mm" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-10",
      sku: "HAN-71400000",
      barcode: "4011097738246",
      name: "Hansgrohe Logis Jednoručna zidna baterija za kadu i tuš",
      slug: "hansgrohe-logis-zidna-baterija-za-kadu",
      brand: "Hansgrohe",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "baterije",
      subcategoryName: "Slavine i baterije",
      price: 11990,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 15,
      wmsLocation: "C-01-02-06",
      shortDescription: "Pouzdana nemačka baterija sa AirPower tehnologijom i keramičkim mešačem.",
      description: "Hansgrohe Logis nudi vrhunsku ergonomiju i dugovečnost. Zidna montaža na standardni razmak 150 mm sa S-priključcima i integrisanim prebacivačem kada/tuš.",
      images: ["/placeholder-faucet.svg"],
      attributes: { zavrsna_obrada: "Hrom sjaj", montaza: "Zidna", kartusa: "Keramički 35mm" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-11",
      sku: "GEB-111300005",
      barcode: "4025416301294",
      name: "Geberit Duofix Delta Ugradni vodokotlić za suvu gradnju 112cm",
      slug: "geberit-duofix-delta-ugradni-vodokotlic",
      brand: "Geberit",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "ugradni-sistemi",
      subcategoryName: "Ugradni sistemi i vodokotlići",
      price: 24900,
      salePrice: 21990,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 11,
      wmsLocation: "C-03-01-01",
      shortDescription: "Samonoseći čelični ugradni element sa Delta rezervoarom za konzolnu WC šolju.",
      description: "Švajcarski standard pouzdanosti. Geberit Duofix element je potpuno zaštićen od kondenzacije i podržava dvokoličinsko ispiranje (3/6L) sa Delta aktivacionim tipkama.",
      images: ["/placeholder-toilet.svg"],
      attributes: { montaza: "Ugradna (skrivena)", materijal: "Plastificirani čelik / PE" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-12",
      sku: "RNB-5004PL-PC",
      barcode: "0779850123490",
      name: "Rain Bird 5004-Plus Rotor rasprskivač 3/4\" sa diznama (40-360°)",
      slug: "rain-bird-5004-plus-rotor-rasprskivac",
      brand: "Rain Bird",
      categorySlug: "navodnjavanje",
      categoryName: "Navodnjavanje i bašta",
      subcategorySlug: "prskalice",
      subcategoryName: "Rasprskivači i rotori",
      price: 2190,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 65,
      wmsLocation: "D-02-01-04",
      shortDescription: "Vodeći svetski rotor za travnjake sa tehnologijom Rain Curtain zavese kapi.",
      description: "Podesivi sektor navodnjavanja od 40° do 360°. Poseduje Flow Shut-off mehanizam koji omogućava isključivanje pojedinačnog rotora bez zaustavljanja cele zone.",
      images: ["/placeholder-sprinkler.svg"],
      attributes: { prikljucak: "3/4\"", domet: "5 - 10 m", materijal: "UV otporna plastika" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-13",
      sku: "GAR-18036",
      barcode: "4078500012356",
      name: "Gardena Baštensko armirano crevo Comfort FLEX 1/2\" 25m",
      slug: "gardena-bastensko-crevo-comfort-flex-1-2-25m",
      brand: "Gardena",
      categorySlug: "navodnjavanje",
      categoryName: "Navodnjavanje i bašta",
      subcategorySlug: "creva",
      subcategoryName: "Baštenska i tehnička creva",
      price: 3690,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 40,
      wmsLocation: "D-01-03-02",
      shortDescription: "Crevo sa Power Grip profilom, otporno na pritisak do 25 bara i uvijanje.",
      description: "Kvalitetno spiralno pletivo osigurava optimalnu fleksibilnost bez prelamanja i gužvanja creva. Ne sadrži ftalate i teške metale.",
      images: ["/placeholder-hose.svg"],
      attributes: { prikljucak: "1/2\"", pritisak: "PN 25", duzina: "25 m" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-14",
      sku: "HNT-PGV101",
      barcode: "0886543210987",
      name: "Hunter PGV-101 Elektromagnetni ventil 1\" Ž-Ž sa kontrolom protoka (24VAC)",
      slug: "hunter-pgv-101-elektromagnetni-ventil-1",
      brand: "Hunter",
      categorySlug: "navodnjavanje",
      categoryName: "Sistemi za navodnjavanje",
      subcategorySlug: "automatika",
      subcategoryName: "Elektroventili i tajmeri",
      price: 3290,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 30,
      wmsLocation: "D-03-02-01",
      shortDescription: "Robusni 24V elektromagnetni ventil za automatsko navodnjavanje sa regulatorom protoka.",
      description: "Industrijski standard za pouzdano upravljanje zonama navodnjavanja. Visokokvalitetna membrana sa dvostrukom ivicom za rad bez curenja.",
      images: ["/placeholder-valve.svg"],
      attributes: { prikljucak: "1\"", napon: "24V AC", protok: "500 - 1500 l/h" },
      isFeatured: false,
      isPromo: false,
    },
  ];

  for (const prod of productsData) {
    const missingAttributes = getMissingRequiredAttributes(prod.subcategorySlug, prod.attributes);
    if (missingAttributes.length > 0) {
      throw new Error("Product " + prod.sku + " is missing required attributes: " + missingAttributes.join(", "));
    }

    await prisma.product.upsert({
      where: { id: prod.id },
      update: {
        name: prod.name,
        price: prod.price,
        salePrice: prod.salePrice,
        stockQuantity: prod.stockQuantity,
      },
      create: {
        ...prod,
        category: { connect: { slug: prod.categorySlug } },
        ...(prod.subcategorySlug
          ? { subcategory: { connect: { slug: prod.subcategorySlug } } }
          : {}),
      },
    });
  }

  // 5. Secure creation of the initial admin user (Requirement 2)
  const adminEmail = process.env.ADMIN_INITIAL_EMAIL || "admin@aquastill.rs";
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD || "Zlatibor2026!";
  const hashedPassword = await bcrypt.hash(adminPassword, 10);

  const existingAdmin = await prisma.user.findUnique({
    where: { email: adminEmail },
  });

  if (!existingAdmin) {
    await prisma.user.create({
      data: {
        name: "Glavni Administrator",
        email: adminEmail,
        password: hashedPassword,
        role: "admin",
      },
    });
    console.log(`Initial admin user created successfully (${adminEmail}).`);
  } else {
    console.log(`Admin user already exists (${adminEmail}).`);
  }

  console.log("Seeding completed successfully.");
}

main()
  .catch((e) => {
    console.error("Error during database seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
