import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database for Aqua Still Zlatibor...");

  // 1. Categories
  const categoriesData = [
    { id: "cat-alati", name: "Alati i oprema", slug: "alati", description: "Profesionalni i hobi električni i ručni alati, pribor i oprema za majstore i radionice.", itemCount: 420, iconName: "wrench" },
    { id: "cat-vodovod", name: "Vodovod i kanalizacija", slug: "vodovod", description: "Cevi, fiting, ventili, pumpe i kompletan materijal za vodovodne instalacije.", itemCount: 380, iconName: "droplet" },
    { id: "cat-kupatila", name: "Kupatilska oprema i sanitarije", slug: "kupatila", description: "Baterije za kadu i lavabo, sanitarije, tuš program i moderna oprema za kupatila.", itemCount: 290, iconName: "bath" },
    { id: "cat-navodnjavanje", name: "Sistemi za navodnjavanje", slug: "navodnjavanje", description: "Sve za profesionalno navodnjavanje voćnjaka, bašti, parkova i plastenika.", itemCount: 215, iconName: "sprout" },
    { id: "cat-grejanje", name: "Grejanje", slug: "grejanje", description: "Oprema i instalacioni materijal za sisteme grejanja.", itemCount: 0, iconName: "flame" },
  ];

  for (const cat of categoriesData) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: { name: cat.name, description: cat.description },
      create: cat,
    });
  }

  // 2. Subcategories
  const subcategoriesData = [
    { id: "sub-aku-busilice", categoryId: "cat-alati", name: "Aku bušilice i odvijači", slug: "aku-busilice", itemCount: 110 },
    { id: "sub-brusilice", categoryId: "cat-alati", name: "Ugaone brusilice", slug: "brusilice", itemCount: 85 },
    { id: "sub-rucni-alat", categoryId: "cat-alati", name: "Ručni alati i ključevi", slug: "rucni-alat", itemCount: 145 },
    { id: "sub-testere", categoryId: "cat-alati", name: "Testere i cirkulari", slug: "testere", itemCount: 80 },
    { id: "sub-cevi", categoryId: "cat-vodovod", name: "Cevi i kanali", slug: "cevi", itemCount: 120 },
    { id: "sub-fiting", categoryId: "cat-vodovod", name: "Fiting i spojnice", slug: "fiting", itemCount: 130 },
    { id: "sub-ventili", categoryId: "cat-vodovod", name: "Kugla ventili i zasuni", slug: "ventili", itemCount: 75 },
    { id: "sub-pumpe-voda", categoryId: "cat-vodovod", name: "Pumpe za vodu i hidrofori", slug: "pumpe-za-vodu", itemCount: 55 },
    { id: "sub-baterije", categoryId: "cat-kupatila", name: "Slavine i baterije", slug: "slavine-i-baterije", itemCount: 110 },
    { id: "sub-sanitarije", categoryId: "cat-kupatila", name: "Sanitarije i ugradni sistemi", slug: "sanitarije", itemCount: 95 },
    { id: "sub-tus-program", categoryId: "cat-kupatila", name: "Tuš kabine i stubovi", slug: "tus-program", itemCount: 50 },
    { id: "sub-namestaj", categoryId: "cat-kupatila", name: "Kupatilski nameštaj", slug: "kupatilski-namestaj", itemCount: 35 },
    { id: "sub-kap-po-kap", categoryId: "cat-navodnjavanje", name: "Sistemi kap po kap", slug: "kap-po-kap", itemCount: 65 },
    { id: "sub-prskalice", categoryId: "cat-navodnjavanje", name: "Rasprskivači i rotori", slug: "prskalice", itemCount: 60 },
    { id: "sub-creva", categoryId: "cat-navodnjavanje", name: "Baštenska i tehnička creva", slug: "creva", itemCount: 50 },
    { id: "sub-automatika", categoryId: "cat-navodnjavanje", name: "Elektroventili i tajmeri", slug: "automatika", itemCount: 40 },
  ];

  for (const sub of subcategoriesData) {
    await prisma.subcategory.upsert({
      where: { id: sub.id },
      update: { name: sub.name },
      create: sub,
    });
  }

  // 3. Brands
  const brandsData = [
    { id: "brand-makita", name: "Makita", slug: "makita" },
    { id: "brand-bosch", name: "Bosch", slug: "bosch" },
    { id: "brand-dewalt", name: "DeWalt", slug: "dewalt" },
    { id: "brand-unior", name: "Unior", slug: "unior" },
    { id: "brand-pestan", name: "Peštan", slug: "pestan" },
    { id: "brand-valvex", name: "Valvex", slug: "valvex" },
    { id: "brand-pedrollo", name: "Pedrollo", slug: "pedrollo" },
    { id: "brand-grohe", name: "Grohe", slug: "grohe" },
    { id: "brand-hansgrohe", name: "Hansgrohe", slug: "hansgrohe" },
    { id: "brand-geberit", name: "Geberit", slug: "geberit" },
    { id: "brand-rain-bird", name: "Rain Bird", slug: "rain-bird" },
    { id: "brand-gardena", name: "Gardena", slug: "gardena" },
    { id: "brand-hunter", name: "Hunter", slug: "hunter" },
  ];

  for (const brand of brandsData) {
    await prisma.brand.upsert({
      where: { id: brand.id },
      update: { name: brand.name },
      create: brand,
    });
  }

  // 4. Products
  const productsData = [
    {
      id: "prod-1",
      sku: "MAK-DHP485Z",
      barcode: "0088381866385",
      name: "Makita DHP485Z Aku udarna bušilica-odvijač 18V (bez baterije i punjača)",
      slug: "makita-dhp485z-aku-udarna-busilica-18v",
      brand: "Makita",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "aku-busilice",
      subcategoryName: "Aku bušilice i odvijači",
      price: 13990,
      salePrice: 11990,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 18,
      wmsLocation: "A-03-02-04",
      shortDescription: "Snažna udarna bušilica sa motorom bez četkica (Brushless), 50 Nm obrtnog momenta.",
      description: "Makita DHP485Z je kompaktna i izuzetno izdržljiva akumulatorska udarna bušilica. Opremljena je motorom bez četkica koji omogućava veću autonomiju rada i duži vek trajanja. Poseduje metalnu brzosteznu glavu 13mm i dvobrzinski prenosnik.",
      images: ["/placeholder-tool.svg"],
      attributes: { napon: "18V", motor: "Brushless (bez četkica)", prihvat: "13 mm", obrtni_moment: "50 Nm", broj_obrtaja: "0-500 / 0-1.900 min-1" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-2",
      sku: "BOS-GSB18V50",
      barcode: "3165140982900",
      name: "Bosch Professional GSB 18V-50 Akumulatorska udarna bušilica",
      slug: "bosch-professional-gsb-18v-50-aku-busilica",
      brand: "Bosch",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "aku-busilice",
      subcategoryName: "Aku bušilice i odvijači",
      price: 17490,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 12,
      wmsLocation: "A-03-02-05",
      shortDescription: "Robustan motor bez četkica za teške poslove bušenja u zidu, drvetu i metalu.",
      description: "Inteligentni Brushless motor direktno komunicira sa elektronikom alata za optimalan rad i zaštitu od preopterećenja. Metalni futer 13 mm pruža maksimalan prenos snage.",
      images: ["/placeholder-tool.svg"],
      attributes: { napon: "18V", motor: "Brushless (bez četkica)", prihvat: "13 mm", obrtni_moment: "50 Nm" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-3",
      sku: "DEW-DWE4206",
      barcode: "5035048538203",
      name: "DeWalt DWE4206 Ugaona električna brusilica 115mm 1010W",
      slug: "dewalt-dwe4206-ugaona-brusilica-115mm-1010w",
      brand: "DeWalt",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "brusilice",
      subcategoryName: "Ugaone brusilice",
      price: 10490,
      salePrice: 9190,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 24,
      wmsLocation: "A-01-04-02",
      shortDescription: "Kompaktna ugaona brusilica visoke efikasnosti sa No-Volt Release zaštitom.",
      description: "Sistem za izbacivanje prašine uklanja većinu čestica iz vazduha koji prolazi kroz motor, sprečavajući oštećenja i habanje. Meki start smanjuje trzaj pri pokretanju.",
      images: ["/placeholder-tool.svg"],
      attributes: { snaga: "850W - 1200W", napon: "230V", prihvat: "M14" },
      isFeatured: false,
      isPromo: true,
    },
    {
      id: "prod-4",
      sku: "UNI-1201CB",
      barcode: "3838909120150",
      name: "Unior Garnitura viljuškasto-okastih ključeva u kartonu 6-22mm (17 kom)",
      slug: "unior-garnitura-viljuskasto-okastih-kljuceva-6-22mm",
      brand: "Unior",
      categorySlug: "alati",
      categoryName: "Alati i oprema",
      subcategorySlug: "rucni-alat",
      subcategoryName: "Ručni alati i ključevi",
      price: 15890,
      salePrice: null,
      vatRate: 0.20,
      unit: "pak",
      inStock: true,
      stockQuantity: 9,
      wmsLocation: "A-02-01-08",
      shortDescription: "Hrom-vanadijumski kovani ključevi krunisani po DIN 3113 standardu.",
      description: "Unior profesionalni ključevi izradjeni od vrhunskog hrom-vanadijum čelika, kovani i u celosti ojačani. Dugovečan i pouzdan radionički komplet.",
      images: ["/placeholder-tool.svg"],
      attributes: { materijal: "Hrom-vanadijum", broj_delova: "17 komada (6-22 mm)" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-5",
      sku: "PES-3SK110-1000",
      barcode: "8605012304912",
      name: "Peštan 3P Niskošumna kanalizaciona cev fi 110 x 1000 mm",
      slug: "pestan-3p-niskosumna-kanalizaciona-cev-110-1000",
      brand: "Peštan",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "cevi",
      subcategoryName: "Cevi i kanali",
      price: 940,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 140,
      wmsLocation: "B-01-01-01",
      shortDescription: "Troslojna bešumna cev za unutrašnju kanalizaciju sa integrisanom zaptivkom.",
      description: "Peštan 3P cevi izrađene su od mineralno ojačanog polipropilena. Pružaju znatno smanjenje buke protoka otpadnih voda i visoku otpornost na hemikalije i toplotu.",
      images: ["/placeholder-pipe.svg"],
      attributes: { precnik: "fi 110", materijal: "PP mineralno ojačan", duzina: "1000 mm" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-6",
      sku: "PES-PPR25-PN20",
      barcode: "8605012308821",
      name: "Peštan PP-R Cev za toplu i hladnu vodu fi 25 mm PN20 (4m)",
      slug: "pestan-ppr-cev-fi-25mm-pn20-4m",
      brand: "Peštan",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "cevi",
      subcategoryName: "Cevi i kanali",
      price: 490,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 220,
      wmsLocation: "B-01-02-03",
      shortDescription: "Polipropilenska cev za vodovodne instalacije, pritisak PN20.",
      description: "Ekološki materijal otporan na kamenac i koroziju. Koristi se za instalaciju pijaće tople i hladne vode u stambenim i industrijskim objektima.",
      images: ["/placeholder-pipe.svg"],
      attributes: { precnik: "fi 25", materijal: "PP-R", pritisak: "PN 20" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-7",
      sku: "VAL-KV12-LEP",
      barcode: "5901234567891",
      name: "Valvex Kugla ventil sa leptir ručkom 1/2\" PN30 Ž-Ž",
      slug: "valvex-kugla-ventil-leptir-rucka-1-2-pn30",
      brand: "Valvex",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "ventili",
      subcategoryName: "Kugla ventili i zasuni",
      price: 680,
      salePrice: 590,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 85,
      wmsLocation: "B-03-01-14",
      shortDescription: "Mesingani kuglasti ventil sa punim protokom i crvenom leptir ručkom.",
      description: "Visokokvalitetni ventil za vodu i grejanje, testiran na radni pritisak do 30 bara. Telo od kovanog niklovanog mesinga.",
      images: ["/placeholder-valve.svg"],
      attributes: { precnik: "1/2\"", materijal: "Mesing", pritisak: "PN 30" },
      isFeatured: false,
      isPromo: true,
    },
    {
      id: "prod-8",
      sku: "PED-TOP2",
      barcode: "8056789012345",
      name: "Pedrollo TOP 2 Potapajuća drenažna pumpa za čistu vodu",
      slug: "pedrollo-top-2-potapajuca-pumpa",
      brand: "Pedrollo",
      categorySlug: "vodovod",
      categoryName: "Vodovod i kanalizacija",
      subcategorySlug: "pumpe-voda",
      subcategoryName: "Pumpe za vodu i hidrofori",
      price: 18990,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 7,
      wmsLocation: "B-04-03-01",
      shortDescription: "Italijanska potapajuća pumpa kapaciteta do 220 l/min (13.2 m³/h).",
      description: "Pedrollo TOP 2 je pogodna za drenažu bistre vode bez abrazivnih čestica. Odlična za pražnjenje poplavljenih podruma, rezervoara i bazena.",
      images: ["/placeholder-pump.svg"],
      attributes: { snaga: "370W", protok: "2000+ l/h", materijal: "Tehopolimer / Inox" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-9",
      sku: "GRO-32815000",
      barcode: "4005176883204",
      name: "Grohe BauLoop Jednoručna stojeća slavina za lavabo",
      slug: "grohe-bauloop-jednorucna-slavina-za-lavabo",
      brand: "Grohe",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "baterije",
      subcategoryName: "Slavine i baterije",
      price: 7990,
      salePrice: 6690,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 32,
      wmsLocation: "C-01-02-03",
      shortDescription: "Elegantna baterija sa Grohe Long-Life hromiranom obradom i EcoJoy perlatorom.",
      description: "Grohe BauLoop kombinuje moderan minimalistički dizajn sa vrhunskom tehnologijom. Opremljena je keramičkim mešačem 28 mm i perlatorom koji štedi do 50% vode.",
      images: ["/placeholder-faucet.svg"],
      attributes: { zavrsna_obrada: "Hrom sjaj", montaza: "Stojeća (na lavabo)", kartusa: "Keramički 28mm" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-10",
      sku: "HAN-71400000",
      barcode: "4011097738246",
      name: "Hansgrohe Logis Jednoručna zidna baterija za kadu i tuš",
      slug: "hansgrohe-logis-zidna-baterija-za-kadu",
      brand: "Hansgrohe",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "baterije",
      subcategoryName: "Slavine i baterije",
      price: 11990,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 15,
      wmsLocation: "C-01-02-06",
      shortDescription: "Pouzdana nemačka baterija sa AirPower tehnologijom i keramičkim mešačem.",
      description: "Hansgrohe Logis nudi vrhunsku ergonomiju i dugovečnost. Zidna montaža na standardni razmak 150 mm sa S-priključcima i integrisanim prebacivačem kada/tuš.",
      images: ["/placeholder-faucet.svg"],
      attributes: { zavrsna_obrada: "Hrom sjaj", montaza: "Zidna", kartusa: "Keramički 35mm" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-11",
      sku: "GEB-111300005",
      barcode: "4025416301294",
      name: "Geberit Duofix Delta Ugradni vodokotlić za suvu gradnju 112cm",
      slug: "geberit-duofix-delta-ugradni-vodokotlic",
      brand: "Geberit",
      categorySlug: "kupatila",
      categoryName: "Kupatilska oprema i sanitarije",
      subcategorySlug: "sanitarije",
      subcategoryName: "Sanitarije i ugradni sistemi",
      price: 24900,
      salePrice: 21990,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 11,
      wmsLocation: "C-03-01-01",
      shortDescription: "Samonoseći čelični ugradni element sa Delta rezervoarom za konzolnu WC šolju.",
      description: "Švajcarski standard pouzdanosti. Geberit Duofix element je potpuno zaštićen od kondenzacije i podržava dvokoličinsko ispiranje (3/6L) sa Delta aktivacionim tipkama.",
      images: ["/placeholder-toilet.svg"],
      attributes: { montaza: "Ugradna (skrivena)", materijal: "Plastificirani čelik / PE" },
      isFeatured: true,
      isPromo: true,
    },
    {
      id: "prod-12",
      sku: "RNB-5004PL-PC",
      barcode: "0779850123490",
      name: "Rain Bird 5004-Plus Rotor rasprskivač 3/4\" sa diznama (40-360°)",
      slug: "rain-bird-5004-plus-rotor-rasprskivac",
      brand: "Rain Bird",
      categorySlug: "navodnjavanje",
      categoryName: "Sistemi za navodnjavanje",
      subcategorySlug: "prskalice",
      subcategoryName: "Rasprskivači i rotori",
      price: 2190,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 65,
      wmsLocation: "D-02-01-04",
      shortDescription: "Vodeći svetski rotor za travnjake sa tehnologijom Rain Curtain zavese kapi.",
      description: "Podesivi sektor navodnjavanja od 40° do 360°. Poseduje Flow Shut-off mehanizam koji omogućava isključivanje pojedinačnog rotora bez zaustavljanja cele zone.",
      images: ["/placeholder-sprinkler.svg"],
      attributes: { prikljucak: "3/4\"", domet: "5 - 10 m", materijal: "UV otporna plastika" },
      isFeatured: true,
      isPromo: false,
    },
    {
      id: "prod-13",
      sku: "GAR-18036",
      barcode: "4078500012356",
      name: "Gardena Baštensko armirano crevo Comfort FLEX 1/2\" 25m",
      slug: "gardena-bastensko-crevo-comfort-flex-1-2-25m",
      brand: "Gardena",
      categorySlug: "navodnjavanje",
      categoryName: "Sistemi za navodnjavanje",
      subcategorySlug: "creva",
      subcategoryName: "Baštenska i tehnička creva",
      price: 3690,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 40,
      wmsLocation: "D-01-03-02",
      shortDescription: "Crevo sa Power Grip profilom, otporno na pritisak do 25 bara i uvijanje.",
      description: "Kvalitetno spiralno pletivo osigurava optimalnu fleksibilnost bez prelamanja i gužvanja creva. Ne sadrži ftalate i teške metale.",
      images: ["/placeholder-hose.svg"],
      attributes: { prikljucak: "1/2\"", pritisak: "PN 25", duzina: "25 m" },
      isFeatured: false,
      isPromo: false,
    },
    {
      id: "prod-14",
      sku: "HNT-PGV101",
      barcode: "0886543210987",
      name: "Hunter PGV-101 Elektromagnetni ventil 1\" Ž-Ž sa kontrolom protoka (24VAC)",
      slug: "hunter-pgv-101-elektromagnetni-ventil-1",
      brand: "Hunter",
      categorySlug: "navodnjavanje",
      categoryName: "Sistemi za navodnjavanje",
      subcategorySlug: "automatika",
      subcategoryName: "Elektroventili i tajmeri",
      price: 3290,
      salePrice: null,
      vatRate: 0.20,
      unit: "kom",
      inStock: true,
      stockQuantity: 30,
      wmsLocation: "D-03-02-01",
      shortDescription: "Robusni 24V elektromagnetni ventil za automatsko navodnjavanje sa regulatorom protoka.",
      description: "Industrijski standard za pouzdano upravljanje zonama navodnjavanja. Visokokvalitetna membrana sa dvostrukom ivicom za rad bez curenja.",
      images: ["/placeholder-valve.svg"],
      attributes: { prikljucak: "1\"", napon: "24V AC", protok: "500 - 1500 l/h" },
      isFeatured: false,
      isPromo: false,
    },
  ];

  for (const prod of productsData) {
    await prisma.product.upsert({
      where: { id: prod.id },
      update: {
        name: prod.name,
        price: prod.price,
        salePrice: prod.salePrice,
        stockQuantity: prod.stockQuantity,
      },
      create: prod as any,
    });
  }

  // 5. Secure creation of the initial admin user (Requirement 2)
  const adminEmail = process.env.ADMIN_INITIAL_EMAIL || "admin@aquastill.rs";
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD || "Zlatibor2026!";
  const hashedPassword = await bcrypt.hash(adminPassword, 10);

  const existingAdmin = await prisma.user.findUnique({
    where: { email: adminEmail },
  });

  if (!existingAdmin) {
    await prisma.user.create({
      data: {
        name: "Glavni Administrator",
        email: adminEmail,
        password: hashedPassword,
        role: "admin",
      },
    });
    console.log(`Initial admin user created successfully (${adminEmail}).`);
  } else {
    console.log(`Admin user already exists (${adminEmail}).`);
  }

  console.log("Seeding completed successfully.");
}

main()
  .catch((e) => {
    console.error("Error during database seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
